---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reana.prefix" . }}-message-broker
  namespace: {{ .Release.Namespace }}
spec:
  ports:
   - port: 5672
     targetPort: 5672
     name: "tcp"
     protocol: TCP
   - port: 15672
     targetPort: 15672
     name: "management"
     protocol: TCP
  selector:
    app: {{ include "reana.prefix" . }}-message-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reana.prefix" . }}-message-broker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "reana.prefix" . }}-message-broker
  template:
    metadata:
      labels:
        app: {{ include "reana.prefix" . }}-message-broker
    spec:
      containers:
      - name: message-broker
        image: {{ .Values.components.reana_message_broker.image }}
        imagePullPolicy: {{ .Values.components.reana_message_broker.imagePullPolicy }}
        ports:
        - containerPort: 5672
          name: tcp
        - containerPort: 15672
          name: management
      {{- if .Values.node_label_infrastructure }}
      {{- $full_label := split "=" .Values.node_label_infrastructure }}
      nodeSelector:
        {{ $full_label._0 }}: {{ $full_label._1 }}
      {{- end }}
