{{- if .Values.components.reana_db.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reana.prefix" . }}-db
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ include "reana.prefix" . }}-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reana.prefix" . }}-db
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "reana.prefix" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "reana.prefix" . }}-db
    spec:
      containers:
      - name: db
        image: postgres:9.6.2
        ports:
        - containerPort: 5432
        env:
        - name: TZ
          value: "Europe/Zurich"
        - name: POSTGRES_DB
          value: reana
        {{- if not .Values.debug.enabled }}
        - name: POSTGRES_USER
          value: reana
        - name: POSTGRES_PASSWORD
          value: reana
        {{- else }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "reana.prefix" . }}-db-secrets
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "reana.prefix" . }}-db-secrets
              key: password
        {{- end }}
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          hostPath:
            path: /var/reana/db
      {{- if .Values.node_label_infrastructure }}
      {{- $full_label := split "=" .Values.node_label_infrastructure }}
      nodeSelector:
        {{ $full_label._0 }}: {{ $full_label._1 }}
      {{- end }}
{{- end }}
